# Site
name: 'Melange'
description: 'Assortment of ideas, opinions, perspectives, experiences & interests.'
logo: 'assets/images/banner.jpg'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'demowebsite'
email: 'isha.melange@gmail.com'
mailchimp-list: 'https://gmail.us2.list-manage.com/subscribe/post?u=b3260b617b54b52395ff92993&amp;id=c3a5b637fa'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    isha:
      name:           Isha
      # site:           https://www.wowthemes.net
      avatar:         assets/images/pic1.jpg
      bio:            "Hi there! This blog is an attempt to organize my thoughts in order to understand the world better. I like to write about my experiences, thoughts, and perspectives. I love a good discussion, I like to know about different viewpoints and opinions regarding any subject matter. I would love to hear your thoughts."
      email:          isha.melange@gmail.com
      twitter:        https://twitter.com/Isha02079331

    # jane:
    #   name:           Jane
    #   site:           https://www.wowthemes.net
    #   avatar:         /assets/images/avatar2.jpg
    #   bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
    #   email:          fakemail@gmail.com
    #   twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]